### ISSUE TITLE
Question regarding the Propagation step

### ISSUE THREAD

**Issue by op-rt** [PhyM73/WaveFunctionCollapse_DASC_project#13]
Dear @PhyM73 ,

Thank you for this efficient and very pythonic port of the original C# algorithm. I learned a lot from it.

A step is still unclear to me, at line 233 during propagation you wrote:

`                    if not set(self[nb].space.keys()).issubset(available):`

Would you mind explaining (even briefly) what is the purpose of this condition ? Why is it necessary that the states of the neighbors (`set(self[nb].space.keys())`) are NOT a subset of the available states at that position (`available`) ?

Regards

**Comment by PhyM73** [comment]
Because if all the states of the position, `nb`,  are available, we don't need to do anything with this one, just moving on the next position. Only if there are some states that are not available, which implys that `set(self[nb].space.keys()))` is not a subset of the available set, we need to modify the statespace of the Kont on this position.

**Comment by op-rt** [comment]
Thank you for the reply and explanation. It all makes sense now.
